model:
    dilation: [2,3,5,7]             # Dilations
    M: 4                            # Filters per dilated convolution
    Lf: 3                           # Size of 1D convolution
    length: 96                      # Length of the input Time Series
    bottleneck_nn: 24               # Number of neurons in the bottleneck
    num_classes: 4                  # Number of classes

    lmd: 3.0450554052335746e-08     # Regularization parameter
    alpha: 0.05                     # Tradeoff between reconstruction (alpha=0) and classification (alpha=1)

train:
    verbose: True                   # Shows details about the training
    shuffle: True                   # Shuffles the training data after each epoch
    batch_size: 64                  # Batch size

    iters: 3000                     # Number of maximum iterations
    early_stopping_rounds: 20       # Number of rounds without improvement before stopping
    lr: 0.0017725138650061408       # Learning rate
