# DATASET
dataset:
  n_train: 1000
  n_valid: 100
  n_test:  100

# MODEL
model:
  M: 4 # number of filters per conv
  Lf: 3 # size of the filters
  length: 96
  bottleneck_nn: 24

  lmd: 0.00001 #1.2164941464151834e-06 #0.00001
  alpha: 0.1

# TRAINING
train:
  verbose: False # print information of the training

  batch_size: 128 # of training and validation, default: 32
  shuffle: True # shuffle training data after each epoch

  iters: 500 # 500
  early_stopping_rounds: 30
  lr: 0.001
